# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0002_auto_20170626_1516'),
        ('serviceProvider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_status', models.BooleanField(default=False)),
                ('daily_availability', models.BooleanField(default=False)),
                ('from_time', models.TimeField()),
                ('until_time', models.TimeField()),
                ('from_day', models.DateField()),
                ('until_day', models.DateField()),
                ('weekly_availability', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceProvider.ServiceProvider')),
            ],
        ),
    ]
