# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider', '0002_auto_20170628_0416'),
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='availability_status',
            new_name='daily',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='from_day',
            new_name='fromday',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='from_time',
            new_name='fromtime',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='daily_availability',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='until_day',
            new_name='untilday',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='until_time',
            new_name='untiltime',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='weekly_availability',
            new_name='weekly',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='service_provider',
        ),
        migrations.AddField(
            model_name='availability',
            name='serviceprovider',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='serviceprovider.Serviceprovider'),
        ),
    ]
