# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_auto_20170628_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='serviceprovider',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='serviceprovider.Serviceprovider'),
        ),
    ]
