# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-12 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_auto_20170628_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='fromtime',
            new_name='endtime',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='untiltime',
            new_name='starttime',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='fromday',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='untilday',
        ),
        migrations.AlterField(
            model_name='availability',
            name='daily',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')]),
        ),
        migrations.AlterField(
            model_name='availability',
            name='serviceprovider',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='serviceProvider.Serviceprovider'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Unavailable')]),
        ),
    ]
