# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-12 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0006_auto_20170712_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='daily',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'No daily availability')], default=5),
        ),
        migrations.AlterField(
            model_name='availability',
            name='serviceprovider',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='serviceProvider.Serviceprovider'),
        ),
    ]
