# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-21 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0008_auto_20170712_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='serviceprovider',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='serviceProvider.Serviceprovider'),
        ),
    ]
