# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-21 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('qualification', models.TextField()),
                ('specialisation', models.TextField()),
                ('fitness_center_name', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
    ]
