# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-26 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=200)),
                ('institution_location', models.CharField(max_length=200)),
                ('institution_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='trainer',
        ),
    ]
