# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_auto_20170626_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='institution_location',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='institution_name',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='institution_type',
            new_name='name',
        ),
    ]
