# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_auto_20170628_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='category',
            field=models.CharField(choices=[('GP', 'General Practitioner'), ('Hospital', 'Hospital'), ('Fitness Centre', 'Fitness Centre')], max_length=200),
        ),
    ]
