# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_auto_20170628_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='creationdate',
            field=models.DateField(default=datetime.datetime(2017, 6, 28, 9, 35, 43, 325370, tzinfo=utc)),
        ),
    ]
