# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_institution_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='creationdate',
            field=models.DateField(),
        ),
    ]
