# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-08 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_auto_20170628_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='status',
            field=models.IntegerField(choices=[(0, 'created'), (1, 'updated'), (2, 'deleted')], default=0),
        ),
        migrations.AlterField(
            model_name='institution',
            name='creationdate',
            field=models.DateField(default=datetime.datetime(2017, 7, 8, 11, 27, 31, 691282, tzinfo=utc)),
        ),
    ]
