# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-12 01:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0008_auto_20170708_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='category',
            field=models.CharField(choices=[(0, 'General Practitioner'), (1, 'Hospital'), (2, 'Fitness Centre'), (3, 'Clinic'), (4, 'School')], max_length=200),
        ),
        migrations.AlterField(
            model_name='institution',
            name='creationdate',
            field=models.DateField(default=datetime.datetime(2017, 7, 12, 1, 54, 47, 363749, tzinfo=utc)),
        ),
    ]
