# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-21 02:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0010_auto_20170712_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='creationdate',
            field=models.DateField(default=datetime.datetime(2017, 7, 21, 2, 28, 40, 287634, tzinfo=utc)),
        ),
    ]
