# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-26 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient',
        ),
    ]
