# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20170627_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='creationdate',
            field=models.DateField(default=datetime.datetime(2017, 6, 28, 9, 33, 25, 279143, tzinfo=utc)),
        ),
    ]
