# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patient_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='creationdate',
            field=models.DateField(),
        ),
    ]
