# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-29 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20170628_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='province',
            field=models.CharField(default='p', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='region',
            field=models.CharField(default='d', max_length=200),
        ),
    ]
