# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-29 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20170629_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='province',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='region',
            field=models.CharField(max_length=200),
        ),
    ]
