# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-02 20:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_auto_20170702_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='creationdate',
            field=models.DateField(default=datetime.datetime(2017, 7, 2, 20, 8, 25, 778145, tzinfo=utc), verbose_name="Patient's record creation date"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='firstname',
            field=models.CharField(max_length=200, verbose_name="Patient's first mame"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastname',
            field=models.CharField(max_length=200, verbose_name="Patient's last mame"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='location',
            field=models.CharField(max_length=200, verbose_name="Patient's location"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='province',
            field=models.CharField(max_length=200, verbose_name="Patient's residential Province"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='region',
            field=models.CharField(max_length=200, verbose_name="Patient's region"),
        ),
    ]
