# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-22 10:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_auto_20170721_0453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['creationdate']},
        ),
        migrations.AlterField(
            model_name='patient',
            name='creationdate',
            field=models.DateField(default=datetime.datetime(2017, 7, 22, 10, 55, 16, 678612, tzinfo=utc), verbose_name="Patient's record creation date"),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together=set([('id', 'identitynumber')]),
        ),
    ]
