# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-22 11:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_auto_20170722_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='creationdate',
            field=models.DateField(default=datetime.datetime(2017, 7, 22, 11, 5, 52, 951229, tzinfo=utc), verbose_name="Patient's record creation date"),
        ),
    ]
