# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('serviceprovidertype', models.CharField(choices=[('Doctor', 'Doctor'), ('Trainer', 'Trainer'), ('Specialist', 'Specialist')], max_length=25)),
                ('qualification', models.CharField(max_length=25)),
                ('speciality', models.CharField(max_length=25)),
                ('creationdate', models.DateField()),
            ],
        ),
    ]
