# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProvider', '0002_auto_20170628_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='serviceprovidertype',
            new_name='category',
        ),
    ]
