# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 10:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider', '0003_auto_20170628_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='creationdate',
            field=models.DateField(default=datetime.datetime(2017, 6, 28, 10, 10, 28, 223924, tzinfo=utc)),
        ),
    ]
