# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-08 10:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('serviceProvider', '0004_auto_20170628_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='status',
            field=models.IntegerField(choices=[(0, 'created'), (2, 'updated'), (3, 'deleted')], default='0'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='creationdate',
            field=models.DateField(default=datetime.datetime(2017, 7, 8, 10, 13, 55, 591727, tzinfo=utc)),
        ),
    ]
