# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-21 02:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider', '0006_auto_20170721_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='creationdate',
            field=models.DateField(default=datetime.datetime(2017, 7, 21, 2, 53, 2, 985105, tzinfo=utc)),
        ),
    ]
