# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 08:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceProvider', '0002_auto_20170628_0416'),
        ('institution', '0002_auto_20170626_1516'),
        ('patient', '0004_auto_20170627_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referaldate', models.DateTimeField(verbose_name=datetime.datetime(2017, 6, 28, 10, 31, 54, 865673))),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
                ('serviceprovider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceProvider.Serviceprovider')),
            ],
        ),
    ]
