# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 08:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referal',
            name='referaldate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 6, 28, 10, 34, 5, 716609)),
        ),
        migrations.AlterField(
            model_name='referal',
            name='serviceprovider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceProvider.Serviceprovider'),
        ),
    ]
