# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referal', '0004_auto_20170628_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referal',
            name='referaldate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='referal',
            name='serviceprovider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceprovider.Serviceprovider'),
        ),
    ]
