# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 10:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referal', '0007_auto_20170628_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referal',
            name='referaldate',
            field=models.DateField(default=datetime.datetime(2017, 6, 28, 12, 10, 28, 226416)),
        ),
        migrations.AlterField(
            model_name='referal',
            name='serviceprovider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceprovider.Serviceprovider'),
        ),
    ]
