# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-21 02:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referal', '0009_auto_20170721_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referal',
            name='referaldate',
            field=models.DateField(default=datetime.datetime(2017, 7, 21, 4, 53, 2, 987345)),
        ),
        migrations.AlterField(
            model_name='referal',
            name='serviceprovider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceprovider.Serviceprovider'),
        ),
    ]
