# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceprovider', '0002_auto_20170628_0416'),
        ('institution', '0003_auto_20170628_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigndate', models.DateTimeField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
                ('serviceprovider', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='serviceprovider.Serviceprovider')),
            ],
        ),
    ]
