# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 09:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assigndate',
        ),
        migrations.AddField(
            model_name='assignment',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 28, 9, 11, 11, 875489, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='serviceprovider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceprovider.Serviceprovider'),
        ),
    ]
