# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20170628_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='serviceprovider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceProvider.Serviceprovider'),
        ),
    ]
