# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-08 13:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20170628_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'active'), (1, 'inactive')], default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 8, 13, 11, 13, 419974, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='serviceprovider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceprovider.Serviceprovider'),
        ),
    ]
